=== munandarh/Tugas-WebService/apotik.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="apotik">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="obat"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="obat">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="ukuran"/>
                <xs:element ref="satuan"/>
                <xs:element ref="jumlah"/>
                <xs:element ref="khasiat"/>
                <xs:element ref="harga"/>
                <xs:element ref="perusahaan"/>
            </xs:sequence>
            <xs:attribute name="Nama" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="kode" type="xs:NCName"/>
    <xs:element name="ukuran" type="xs:NMTOKEN"/>
    <xs:element name="satuan" type="xs:NCName"/>
    <xs:element name="jumlah" type="xs:integer"/>
    <xs:element name="khasiat" type="xs:string"/>
    <xs:element name="harga">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="per" use="required" type="xs:NCName"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="perusahaan">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alamat"/>
                <xs:element ref="email"/>
            </xs:sequence>
            <xs:attribute name="Nama" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="alamat" type="xs:NCName"/>
    <xs:element name="email">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">
    			<xs:pattern
    				value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})">
    			</xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
</xs:schema>

=== munandarh/Tugas-WebService/apotik.xml
<?xml version="1.0" encoding="UTF-8"?>
<apotik xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="apotik.xsd">
<obat Nama="Paracetamol">
	<kode>G202</kode>
	<ukuran>500MG</ukuran>
	<satuan>Strip</satuan>
	<jumlah>8</jumlah>
	<khasiat>Meringankan Demam</khasiat>
	<harga per="satuan">10000</harga>
	<perusahaan Nama="PT.PIM PHARMACEUTICALS">
		<alamat>Pasuruan</alamat>
		<email>pimphar@gmail.com</email>
	</perusahaan>
</obat>

<obat Nama="Progmag">
	<kode>L328</kode>
	<ukuran>500MG</ukuran>
	<satuan>Strip</satuan>
	<jumlah>12</jumlah>
	<khasiat>Meringankan Asam Lambung</khasiat>
	<harga per="satuan">8000</harga>
	<perusahaan Nama="PT.KALBE FARMA">
		<alamat>Bekasi</alamat>
		<email>kalbefarma@gmail.com</email>
	</perusahaan>
</obat>

<obat Nama="Mefinal">
	<kode>D473</kode>
	<ukuran>500MG</ukuran>
	<satuan>Strip</satuan>
	<jumlah>12</jumlah>
	<khasiat>Meringankan Rasa Sakit</khasiat>
	<harga per="satuan">25000</harga>
	<perusahaan Nama="PT.CAPRIFARMINDO">
		<alamat>Bandung</alamat>
		<email>farmindo@gmail.com</email>
	</perusahaan>
</obat>

<obat Nama="Grafix">
	<kode>S247</kode>
	<ukuran>500MG</ukuran>
	<satuan>Strip</satuan>
	<jumlah>10</jumlah>
	<khasiat>Meringankan Demam</khasiat>
	<harga per="satuan">15000</harga>
	<perusahaan Nama="PT.GARCIA">
		<alamat>Bandung</alamat>
		<email>garcia@gmail.com</email>
	</perusahaan>
</obat>

<obat Nama="Witranal">
	<kode>J428</kode>
	<ukuran>500MG</ukuran>
	<satuan>Strip</satuan>
	<jumlah>10</jumlah>
	<khasiat>Meringankan Flu</khasiat>
	<harga per="satuan">18000</harga>
	<perusahaan Nama="PT.ITRASAL">
		<alamat>Semarang</alamat>
		<email>itrasal@gmail.com</email>
	</perusahaan>
</obat>
</apotik>
